# Generated by Django 5.0.1 on 2025-07-04 16:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Share your thoughts (max 500 characters)', validators=[django.core.validators.MaxLengthValidator(500)])),
                ('emotion', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('hopeful', 'Hopeful'), ('neutral', 'Neutral')], default='neutral', max_length=20)),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], default='neutral', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField()),
                ('is_flagged', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('inappropriate', 'Inappropriate Content'), ('spam', 'Spam'), ('hate', 'Hate Speech'), ('other', 'Other')], max_length=20)),
                ('details', models.TextField(blank=True)),
                ('reporter_ip', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('thought', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='thoughtify.thought')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
