# Generated by Django 4.2.23 on 2025-07-05 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thoughtify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftThought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=280)),
                ('session_key', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='EmotionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_code', models.CharField(max_length=4, unique=True)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('show_public_thoughts', models.BooleanField(default=True)),
                ('last_daily_thought', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='report',
            name='thought',
        ),
        migrations.RemoveField(
            model_name='thought',
            name='emotion',
        ),
        migrations.RemoveField(
            model_name='thought',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='thought',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='thought',
            name='is_flagged',
        ),
        migrations.AddField(
            model_name='thought',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thought',
            name='is_daily_thought',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thought',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='thought',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='thought',
            name='content',
            field=models.CharField(max_length=280),
        ),
        migrations.AlterField(
            model_name='thought',
            name='sentiment',
            field=models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', max_length=10),
        ),
        migrations.AddIndex(
            model_name='thought',
            index=models.Index(fields=['-created_at'], name='thoughtify__created_6e3a78_idx'),
        ),
        migrations.AddIndex(
            model_name='thought',
            index=models.Index(fields=['author', '-created_at'], name='thoughtify__author__5a5256_idx'),
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='draftthought',
            name='emotion_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='thoughtify.emotiontag'),
        ),
        migrations.AddField(
            model_name='thought',
            name='emotion_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='thoughtify.emotiontag'),
        ),
    ]
